/* Scenario lab, practice, mastery assessment, results, progress, glossary, resources, and about screens. */
(function () {
  'use strict';
  const A = window.MLC;
  const { D, state, screens, icon, escapeHTML: e, screenHeader, screenFooter, objectiveTag, statusChip, progressRing, completionMetrics, xpTotal, earnedBadges, objectiveStats, save, render, navigate, markLesson, toast, confetti, uniquePush } = A;

  function categoryMeta(value) {
    return {
      supervised: { label: 'Supervised learning', icon: 'tags', color: 'cyan', screen: 'supervised', cue: 'Known target labels' },
      unsupervised: { label: 'Unsupervised learning', icon: 'cluster', color: 'violet', screen: 'unsupervised', cue: 'Structure without targets' },
      reinforcement: { label: 'Reinforcement learning', icon: 'gamepad', color: 'emerald', screen: 'reinforcement', cue: 'Actions and rewards over time' }
    }[value];
  }

  function scenarioRecord(scenario) {
    if (!state.scenario.answers[scenario.id]) state.scenario.answers[scenario.id] = {};
    return state.scenario.answers[scenario.id];
  }

  A.handleScenarioCategory = function (value) {
    const scenario = D.scenarios[state.scenario.current];
    const record = scenarioRecord(scenario);
    record.category = value;
    record.categoryCorrect = value === scenario.category;
    state.scenario.stage = 'category-feedback';
    save(); render({ preserveFocus: true });
    toast(record.categoryCorrect ? 'Correct category. Now choose an algorithm.' : 'Review the training signal before choosing an algorithm.', record.categoryCorrect ? 'success' : 'error');
  };

  A.handleScenarioAlgorithm = function (value) {
    const scenario = D.scenarios[state.scenario.current];
    const record = scenarioRecord(scenario);
    record.algorithm = value;
    record.algorithmCorrect = value === scenario.algorithm;
    state.scenario.stage = 'algorithm-feedback';
    uniquePush(state.scenario.completed, scenario.id);
    save(); render({ preserveFocus: true });
    toast(record.algorithmCorrect ? 'Strong match. Read the rationale before continuing.' : 'The task type fits, but another algorithm is a better match.', record.algorithmCorrect ? 'success' : 'error');
  };

  A.nextScenario = function () {
    if (state.scenario.current < D.scenarios.length - 1) {
      state.scenario.current += 1;
      state.scenario.stage = 'category';
      save(); render();
    } else {
      markLesson('scenario', true);
      save(); toast('Scenario Lab complete. Your decisions are saved.'); confetti(); render();
    }
  };

  function scenarioOption(category) {
    const meta = categoryMeta(category);
    return `<button class="choice-card glass-card rounded-3xl p-5 text-left" data-action="scenario-category" data-value="${category}"><span class="icon-shell">${icon(meta.icon, 'h-5 w-5')}</span><h3 class="mt-4 font-black text-theme">${meta.label}</h3><p class="mt-2 text-xs leading-5 text-muted-theme">${meta.cue}</p><span class="mt-4 flex items-center gap-1 text-xs font-black text-cyan-300">Choose ${icon('arrowright', 'h-4 w-4')}</span></button>`;
  }

  function scenarioSummary() {
    const categoryCorrect = D.scenarios.filter(s => state.scenario.answers[s.id] && state.scenario.answers[s.id].categoryCorrect).length;
    const algorithmCorrect = D.scenarios.filter(s => state.scenario.answers[s.id] && state.scenario.answers[s.id].algorithmCorrect).length;
    return `<section class="mesh-panel rounded-3xl border border-emerald-300/20 p-6 sm:p-8"><div class="grid items-center gap-7 lg:grid-cols-[1fr_auto]"><div><span class="inline-flex items-center gap-2 rounded-full bg-emerald-400/10 px-3 py-1.5 text-xs font-black text-emerald-200">${icon('check', 'h-4 w-4')} Lab complete</span><h2 class="mt-4 text-3xl font-black text-white">You made all four design decisions.</h2><p class="mt-3 max-w-2xl leading-7 text-slate-300">Use the evidence below to decide whether to continue to practice or revisit category and algorithm concepts first.</p><div class="mt-6 flex flex-wrap gap-3"><button class="primary-button" data-nav="practice">Continue to guided practice ${icon('arrowright', 'h-5 w-5')}</button><button class="secondary-button" data-action="scenario-reset">Run lab again</button></div></div><div class="grid grid-cols-2 gap-3"><div class="rounded-3xl border border-white/10 bg-slate-950/35 p-5 text-center"><p class="text-3xl font-black text-cyan-200">${categoryCorrect}/4</p><p class="mt-1 text-xs font-bold text-slate-400">Category matches</p></div><div class="rounded-3xl border border-white/10 bg-slate-950/35 p-5 text-center"><p class="text-3xl font-black text-violet-200">${algorithmCorrect}/4</p><p class="mt-1 text-xs font-bold text-slate-400">Algorithm matches</p></div></div></div></section>
      <section class="mt-6 grid gap-4 md:grid-cols-2">${D.scenarios.map(s => { const r = state.scenario.answers[s.id] || {}; const both = r.categoryCorrect && r.algorithmCorrect; return `<article class="glass-card rounded-3xl p-5"><div class="flex items-start gap-3"><span class="grid h-10 w-10 place-items-center rounded-2xl ${both ? 'bg-emerald-400/10 text-emerald-300' : 'bg-amber-300/10 text-amber-300'}">${icon(both ? 'check' : 'question', 'h-5 w-5')}</span><div><h3 class="font-black text-theme">${e(s.title)}</h3><p class="mt-1 text-xs text-muted-theme">Correct match: ${e(categoryMeta(s.category).label)} + ${e(D.algorithms.find(a => a.id === s.algorithm).name)}</p></div></div></article>`; }).join('')}</section>`;
  }

  screens.scenario = function () {
    if (state.scenario.completed.length >= D.scenarios.length && state.completedLessons.includes('scenario')) {
      return `${screenHeader('scenario', 'Your completed cases remain available as evidence. Restart the lab to make the decisions again without losing your best practice or quiz records.', objectiveTag('O2'))}${scenarioSummary()}${screenFooter('scenario')}`;
    }
    const scenario = D.scenarios[state.scenario.current];
    const record = scenarioRecord(scenario);
    const stage = state.scenario.stage;
    const correctAlgorithm = D.algorithms.find(a => a.id === scenario.algorithm);
    const distractors = [scenario.distractor, scenario.category === 'reinforcement' ? 'decision-tree' : 'qlearning', scenario.category === 'unsupervised' ? 'pca' : 'kmeans'];
    const algorithmIds = Array.from(new Set([scenario.algorithm, ...distractors])).slice(0, 3);
    const selectedCategory = record.category ? categoryMeta(record.category) : null;
    const progress = Math.round((state.scenario.completed.length / D.scenarios.length) * 100);
    return `${screenHeader('scenario', 'Each case branches in two stages. First identify the learning category from the training signal; then select an algorithm by matching the required output and constraints.', objectiveTag('O2'))}
      <section class="mb-6 flex items-center gap-4"><div class="h-2 flex-1 overflow-hidden rounded-full bg-slate-800"><div class="h-full rounded-full bg-gradient-to-r from-cyan-400 to-violet-400 transition-all" style="width:${Math.max(progress, 5)}%"></div></div><span class="text-xs font-black text-muted-theme">Case ${state.scenario.current + 1} of ${D.scenarios.length}</span></section>
      <section class="mesh-panel rounded-3xl border border-cyan-300/20 p-5 sm:p-7"><div class="flex flex-col gap-5 sm:flex-row sm:items-start"><span class="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-cyan-300 text-slate-950">${icon(scenario.icon, 'h-7 w-7')}</span><div><p class="text-xs font-black uppercase tracking-[.16em] text-cyan-200">Authentic case</p><h2 class="mt-1 text-2xl font-black text-white">${e(scenario.title)}</h2><p class="mt-3 max-w-4xl leading-7 text-slate-300">${e(scenario.prompt)}</p></div></div></section>
      ${stage === 'category' ? `<section class="mt-7"><p class="text-xs font-black uppercase tracking-[.16em] text-violet-300">Decision 1 of 2</p><h2 class="mt-2 text-2xl font-black text-theme">Which learning category matches the evidence?</h2><p class="mt-2 text-sm text-muted-theme">Focus on what information is available during learning—not on the industry or topic.</p><div class="mt-5 grid gap-4 md:grid-cols-3">${['supervised','unsupervised','reinforcement'].map(scenarioOption).join('')}</div></section>` : ''}
      ${stage === 'category-feedback' ? `<section class="mt-7 rounded-3xl border p-5 sm:p-6 ${record.categoryCorrect ? 'feedback-correct' : 'feedback-incorrect'}"><div class="flex items-start gap-4"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${record.categoryCorrect ? 'bg-emerald-400/10 text-emerald-300' : 'bg-rose-400/10 text-rose-300'}">${icon(record.categoryCorrect ? 'check' : 'question', 'h-5 w-5')}</span><div class="flex-1"><p class="text-xs font-black uppercase tracking-[.14em] ${record.categoryCorrect ? 'text-emerald-300' : 'text-rose-300'}">${record.categoryCorrect ? 'Category match' : 'Category mismatch'}</p><h2 class="mt-1 text-xl font-black text-theme">${record.categoryCorrect ? `${selectedCategory.label} is correct.` : `The best category is ${categoryMeta(scenario.category).label}.`}</h2><p class="mt-3 leading-7 text-muted-theme">${e(scenario.categoryWhy)}</p><div class="mt-5 flex flex-wrap gap-3">${record.categoryCorrect ? '' : `<button class="secondary-button" data-nav="${categoryMeta(scenario.category).screen}">Review ${categoryMeta(scenario.category).label}</button>`}<button class="primary-button" data-action="scenario-continue" data-stage="algorithm">Choose an algorithm ${icon('arrowright', 'h-5 w-5')}</button></div></div></div></section>` : ''}
      ${stage === 'algorithm' ? `<section class="mt-7"><div class="flex flex-wrap items-center gap-2"><span class="text-xs font-black uppercase tracking-[.16em] text-violet-300">Decision 2 of 2</span><span class="rounded-full bg-white/5 px-2.5 py-1 text-xs font-bold text-muted-theme">Category: ${categoryMeta(scenario.category).label}</span></div><h2 class="mt-2 text-2xl font-black text-theme">Which algorithm is the strongest introductory match?</h2><p class="mt-2 text-sm leading-6 text-muted-theme">Choose based on the output, data, explainability needs, and decision context. More than one model could be evaluated in a real project; select the clearest fit here.</p><div class="mt-5 grid gap-4 md:grid-cols-3">${algorithmIds.map(id => { const a = D.algorithms.find(item => item.id === id); return `<button class="choice-card glass-card rounded-3xl p-5 text-left" data-action="scenario-algorithm" data-value="${a.id}"><span class="icon-shell">${icon(a.icon, 'h-5 w-5')}</span><p class="mt-4 text-[10px] font-black uppercase tracking-[.14em] text-cyan-300">${e(a.task)}</p><h3 class="mt-1 font-black text-theme">${e(a.name)}</h3><p class="mt-2 text-xs leading-5 text-muted-theme">${e(a.tagline)}</p><span class="mt-4 flex items-center gap-1 text-xs font-black text-cyan-300">Select ${icon('arrowright', 'h-4 w-4')}</span></button>`; }).join('')}</div></section>` : ''}
      ${stage === 'algorithm-feedback' ? `<section class="mt-7 rounded-3xl border p-5 sm:p-6 ${record.algorithmCorrect ? 'feedback-correct' : 'feedback-incorrect'}"><div class="flex items-start gap-4"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${record.algorithmCorrect ? 'bg-emerald-400/10 text-emerald-300' : 'bg-rose-400/10 text-rose-300'}">${icon(record.algorithmCorrect ? 'check' : 'question', 'h-5 w-5')}</span><div class="flex-1"><p class="text-xs font-black uppercase tracking-[.14em] ${record.algorithmCorrect ? 'text-emerald-300' : 'text-rose-300'}">${record.algorithmCorrect ? 'Strong algorithm match' : 'Better match available'}</p><h2 class="mt-1 text-xl font-black text-theme">${record.algorithmCorrect ? `${correctAlgorithm.name} fits the task.` : `A clearer match is ${correctAlgorithm.name}.`}</h2><p class="mt-3 leading-7 text-muted-theme">${e(scenario.algorithmWhy)}</p><div class="mt-5 grid gap-3 sm:grid-cols-3"><div class="rounded-2xl border border-theme bg-white/5 p-3"><p class="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">Input</p><p class="mt-1 text-xs leading-5 text-theme">${e(correctAlgorithm.input)}</p></div><div class="rounded-2xl border border-theme bg-white/5 p-3"><p class="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">Output</p><p class="mt-1 text-xs leading-5 text-theme">${e(correctAlgorithm.output)}</p></div><div class="rounded-2xl border border-theme bg-white/5 p-3"><p class="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">Watch for</p><p class="mt-1 text-xs leading-5 text-theme">${e(correctAlgorithm.watchFor)}</p></div></div><div class="mt-5 flex flex-wrap gap-3">${record.algorithmCorrect ? '' : `<button class="secondary-button" data-action="scenario-continue" data-stage="algorithm">Try a different algorithm</button><button class="secondary-button" data-nav="algorithms">Review explorer</button>`}<button class="primary-button" data-action="scenario-next">${state.scenario.current === D.scenarios.length - 1 ? 'Finish lab' : 'Next case'} ${icon('arrowright', 'h-5 w-5')}</button></div></div></div></section>` : ''}
      ${screenFooter('scenario')}`;
  };

  function practiceScore() {
    return D.practiceQuestions.reduce((sum, q, index) => sum + (Number(state.practice.answers[index]) === q.answer ? 1 : 0), 0);
  }

  function practiceSummary() {
    const score = practiceScore();
    const o1Questions = D.practiceQuestions.map((q, i) => ({ ...q, i })).filter(q => q.objective === 'O1');
    const o2Questions = D.practiceQuestions.map((q, i) => ({ ...q, i })).filter(q => q.objective === 'O2');
    const objectiveScore = questions => questions.filter(q => Number(state.practice.answers[q.i]) === q.answer).length;
    return `<section class="mesh-panel rounded-3xl border ${score >= 5 ? 'border-emerald-300/20' : 'border-amber-300/20'} p-6 sm:p-8"><div class="grid items-center gap-7 lg:grid-cols-[1fr_auto]"><div><span class="inline-flex items-center gap-2 rounded-full ${score >= 5 ? 'bg-emerald-400/10 text-emerald-200' : 'bg-amber-300/10 text-amber-100'} px-3 py-1.5 text-xs font-black">${icon(score >= 5 ? 'check' : 'question', 'h-4 w-4')} Guided practice complete</span><h2 class="mt-4 text-3xl font-black text-white">${score >= 5 ? 'You are ready for the mastery check.' : 'One more practice pass is recommended.'}</h2><p class="mt-3 max-w-2xl leading-7 text-slate-300">Practice provides explanatory feedback and allows unlimited retries. The mastery check records your performance without item-level feedback until submission.</p><div class="mt-6 flex flex-wrap gap-3"><button class="primary-button" data-nav="quiz">Open mastery check ${icon('arrowright', 'h-5 w-5')}</button><button class="secondary-button" data-action="practice-reset">Practice again</button></div></div><div class="rounded-3xl border border-white/10 bg-slate-950/35 p-6 text-center"><p class="text-5xl font-black ${score >= 5 ? 'text-emerald-300' : 'text-amber-300'}">${score}<span class="text-xl text-slate-400">/${D.practiceQuestions.length}</span></p><p class="mt-2 text-xs font-black uppercase tracking-[.14em] text-slate-400">This attempt</p><p class="mt-3 text-xs text-slate-400">Best: ${state.practice.best}/${D.practiceQuestions.length}</p></div></div></section>
      <section class="mt-6 grid gap-4 sm:grid-cols-2"><div class="glass-card rounded-3xl p-5"><div class="flex items-center justify-between"><span>${objectiveTag('O1')}</span><strong class="text-xl text-theme">${objectiveScore(o1Questions)}/${o1Questions.length}</strong></div><p class="mt-3 text-sm leading-6 text-muted-theme">${objectiveScore(o1Questions) === o1Questions.length ? 'Category distinctions are stable in this practice set.' : 'Review the training signal: labels, no labels, or action-and-reward interaction.'}</p><button class="secondary-button mt-4 w-full text-xs" data-nav="foundations">Review category decision rule</button></div><div class="glass-card rounded-3xl p-5"><div class="flex items-center justify-between"><span>${objectiveTag('O2')}</span><strong class="text-xl text-theme">${objectiveScore(o2Questions)}/${o2Questions.length}</strong></div><p class="mt-3 text-sm leading-6 text-muted-theme">${objectiveScore(o2Questions) === o2Questions.length ? 'Algorithm-to-task matches are stable in this practice set.' : 'Review whether the output is a class, number, cluster, compressed representation, or action policy.'}</p><button class="secondary-button mt-4 w-full text-xs" data-nav="algorithms">Review algorithm explorer</button></div></section>`;
  }

  screens.practice = function () {
    if (state.practice.complete) {
      return `${screenHeader('practice', 'Your best guided-practice score is retained. Repeat the activity for more feedback or continue when you are ready.', objectiveTag('O2'))}${practiceSummary()}${screenFooter('practice')}`;
    }
    const q = D.practiceQuestions[state.practice.index];
    const selected = state.practice.answers[state.practice.index];
    const answered = selected !== undefined;
    const correct = answered && Number(selected) === q.answer;
    return `${screenHeader('practice', 'This is low-stakes rehearsal. Select one answer, read the explanation, and use the remediation button whenever a misconception appears.', `<span class="flex gap-2">${objectiveTag('O1')}${objectiveTag('O2')}</span>`)}
      <section class="mb-6"><div class="flex items-center justify-between text-xs font-black text-muted-theme"><span>Question ${state.practice.index + 1} of ${D.practiceQuestions.length}</span><span>${Object.keys(state.practice.answers).length} answered</span></div><div class="mt-2 flex gap-1.5">${D.practiceQuestions.map((item, i) => `<span class="h-2 flex-1 rounded-full ${i < state.practice.index ? 'bg-emerald-400' : i === state.practice.index ? 'bg-cyan-400' : 'bg-slate-700'}"></span>`).join('')}</div></section>
      <section class="glass-card rounded-3xl p-5 sm:p-7"><div class="flex flex-wrap items-center justify-between gap-3"><span>${objectiveTag(q.objective)}</span><span class="rounded-full bg-white/5 px-3 py-1 text-xs font-bold text-muted-theme">Immediate feedback</span></div><h2 class="mt-5 text-xl font-black leading-8 text-theme sm:text-2xl">${e(q.prompt)}</h2><div class="mt-6 grid gap-3">${q.options.map((option, i) => { let cls = 'choice-card border-theme bg-white/5'; if (answered) { if (i === q.answer) cls = 'choice-card correct'; else if (i === Number(selected) && !correct) cls = 'choice-card incorrect'; } return `<button class="${cls} flex w-full items-start gap-3 rounded-2xl border p-4 text-left" data-action="practice-answer" data-value="${i}" ${answered ? 'disabled' : ''}><span class="grid h-8 w-8 shrink-0 place-items-center rounded-full border border-theme text-xs font-black text-muted-theme">${String.fromCharCode(65 + i)}</span><span class="pt-1 text-sm font-bold leading-6 text-theme">${e(option)}</span></button>`; }).join('')}</div>
      ${answered ? `<div class="mt-6 rounded-2xl border p-5 ${correct ? 'feedback-correct' : 'feedback-incorrect'}" aria-live="polite"><div class="flex items-start gap-3"><span class="grid h-9 w-9 shrink-0 place-items-center rounded-xl ${correct ? 'bg-emerald-400/10 text-emerald-300' : 'bg-rose-400/10 text-rose-300'}">${icon(correct ? 'check' : 'question', 'h-5 w-5')}</span><div><h3 class="font-black text-theme">${correct ? 'Correct reasoning' : 'Correct the mental model'}</h3><p class="mt-2 text-sm leading-6 text-muted-theme">${e(correct ? q.explanation : q.misconception)}</p>${!correct ? `<button class="secondary-button mt-4 min-h-0 px-3 py-2 text-xs" data-nav="${q.objective === 'O1' ? 'foundations' : 'algorithms'}">Review ${q.objective === 'O1' ? 'category decision guide' : 'algorithm matches'} ${icon('arrowright', 'h-4 w-4')}</button>` : ''}</div></div></div>` : ''}
      <div class="mt-6 flex flex-col-reverse gap-3 border-t border-theme pt-5 sm:flex-row sm:justify-between"><button class="secondary-button" data-nav="scenario">${icon('arrowleft', 'h-5 w-5')} Back to lab</button><button class="primary-button" data-action="practice-next" ${answered ? '' : 'disabled'}>${state.practice.index === D.practiceQuestions.length - 1 ? 'Finish practice' : 'Next question'} ${icon('arrowright', 'h-5 w-5')}</button></div></section>
      ${screenFooter('practice')}`;
  };

  screens.quiz = function () {
    if (state.quiz.submitted) {
      return `${screenHeader('quiz', 'Your most recent attempt is complete. Open Results for objective-level evidence, review every item, or begin another attempt.', objectiveTag('O2'))}<section class="mesh-panel rounded-3xl border border-cyan-300/20 p-6 sm:p-8"><div class="grid items-center gap-7 md:grid-cols-[1fr_auto]"><div><span class="inline-flex items-center gap-2 rounded-full bg-cyan-400/10 px-3 py-1.5 text-xs font-black text-cyan-100">${icon('clipboard', 'h-4 w-4')} Assessment submitted</span><h2 class="mt-4 text-3xl font-black text-white">Most recent score: ${state.quiz.lastPercent}%</h2><p class="mt-3 leading-7 text-slate-300">The mastery criterion is 80%. Results separates performance by objective and recommends specific review screens.</p><div class="mt-6 flex flex-wrap gap-3"><button class="primary-button" data-nav="results">View results and review ${icon('arrowright', 'h-5 w-5')}</button><button class="secondary-button" data-action="quiz-retry">Begin another attempt</button></div></div>${progressRing(state.quiz.lastPercent, 110)}</div></section>${screenFooter('quiz')}`;
    }
    if (!state.quiz.started) {
      return `${screenHeader('quiz', 'The mastery check contains eight single-answer questions: four aligned to category classification and four aligned to algorithm selection.', `<span class="flex gap-2">${objectiveTag('O1')}${objectiveTag('O2')}</span>`)}
        <section class="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><article class="glass-card rounded-3xl p-6 sm:p-7"><span class="icon-shell">${icon('clipboard', 'h-6 w-6')}</span><h2 class="mt-5 text-2xl font-black text-theme">Assessment directions</h2><ol class="mt-5 space-y-4 text-sm leading-6 text-muted-theme"><li class="flex gap-3"><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-cyan-400/10 font-black text-cyan-300">1</span><span>Select one answer for each of the eight questions. You may move backward and forward before submitting.</span></li><li class="flex gap-3"><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-cyan-400/10 font-black text-cyan-300">2</span><span>Practice feedback is hidden during the attempt. Explanations appear in Results after submission.</span></li><li class="flex gap-3"><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-cyan-400/10 font-black text-cyan-300">3</span><span>Earn 80% or higher overall. Review objective scores even when the total meets mastery.</span></li><li class="flex gap-3"><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-cyan-400/10 font-black text-cyan-300">4</span><span>Retake as needed. Your best score and attempt history remain in Progress.</span></li></ol><button class="primary-button mt-7 w-full py-4" data-action="quiz-start">Start mastery check ${icon('arrowright', 'h-5 w-5')}</button></article><aside class="space-y-4"><div class="mesh-panel rounded-3xl border border-violet-300/20 p-5"><p class="text-xs font-black uppercase tracking-[.16em] text-violet-200">Mastery standard</p><p class="mt-2 text-5xl font-black text-white">80<span class="text-2xl text-slate-400">%</span></p><p class="mt-2 text-sm leading-6 text-slate-300">At least 7 of 8 questions correct reaches the overall criterion.</p></div><div class="rounded-3xl border border-amber-300/20 bg-amber-300/10 p-5"><h2 class="flex items-center gap-2 font-black text-theme">${icon('shield', 'h-5 w-5 text-amber-300')} Before you begin</h2><p class="mt-2 text-sm leading-6 text-muted-theme">Complete Guided Practice first. Close other distractions, read every scenario for its training signal, and identify the required output before choosing an algorithm.</p><button class="secondary-button mt-4 w-full text-xs" data-nav="practice">Return to guided practice</button></div></aside></section>
        ${screenFooter('quiz')}`;
    }
    const q = D.quizQuestions[state.quiz.index];
    const selected = state.quiz.answers[state.quiz.index];
    const answeredCount = Object.keys(state.quiz.answers).length;
    return `${screenHeader('quiz', 'Choose the strongest answer. Explanations remain hidden until you submit all eight questions.', objectiveTag(q.objective))}
      <section class="mb-6"><div class="flex items-center justify-between text-xs font-black text-muted-theme"><span>Question ${state.quiz.index + 1} of ${D.quizQuestions.length}</span><span>${answeredCount}/${D.quizQuestions.length} answered</span></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-slate-800"><div class="h-full rounded-full bg-gradient-to-r from-cyan-400 to-violet-400 transition-all" style="width:${Math.round(((state.quiz.index + 1) / D.quizQuestions.length) * 100)}%"></div></div><div class="mt-3 flex flex-wrap gap-2" aria-label="Question navigation">${D.quizQuestions.map((item, i) => `<button class="grid h-8 w-8 place-items-center rounded-full border text-xs font-black ${i === state.quiz.index ? 'border-cyan-300 bg-cyan-300 text-slate-950' : state.quiz.answers[i] !== undefined ? 'border-emerald-300/40 bg-emerald-400/10 text-emerald-300' : 'border-theme bg-white/5 text-muted-theme'}" data-action="${i > state.quiz.index ? 'quiz-next' : 'quiz-prev'}" ${Math.abs(i-state.quiz.index) === 1 ? '' : 'disabled'} aria-label="Question ${i+1}${state.quiz.answers[i] !== undefined ? ', answered' : ''}">${i+1}</button>`).join('')}</div></section>
      <section class="glass-card rounded-3xl p-5 sm:p-7"><div class="flex flex-wrap items-center justify-between gap-3"><span>${objectiveTag(q.objective)}</span><span class="rounded-full bg-white/5 px-3 py-1 text-xs font-bold text-muted-theme">No feedback until submission</span></div><h2 class="mt-5 text-xl font-black leading-8 text-theme sm:text-2xl">${e(q.prompt)}</h2><fieldset class="mt-6 grid gap-3"><legend class="sr-only">Answer choices</legend>${q.options.map((option, i) => `<button class="choice-card ${Number(selected) === i ? 'selected' : 'border-theme bg-white/5'} flex w-full items-start gap-3 rounded-2xl border p-4 text-left" data-action="quiz-answer" data-value="${i}"><span class="grid h-8 w-8 shrink-0 place-items-center rounded-full border border-theme text-xs font-black text-muted-theme">${String.fromCharCode(65 + i)}</span><span class="pt-1 text-sm font-bold leading-6 text-theme">${e(option)}</span>${Number(selected) === i ? `<span class="ml-auto text-cyan-300">${icon('check', 'h-5 w-5')}</span>` : ''}</button>`).join('')}</fieldset><div class="mt-7 flex flex-col-reverse gap-3 border-t border-theme pt-5 sm:flex-row sm:justify-between"><button class="secondary-button" data-action="quiz-prev" ${state.quiz.index === 0 ? 'disabled' : ''}>${icon('arrowleft', 'h-5 w-5')} Previous</button>${state.quiz.index < D.quizQuestions.length - 1 ? `<button class="primary-button" data-action="quiz-next">Next question ${icon('arrowright', 'h-5 w-5')}</button>` : `<button class="primary-button" data-action="quiz-submit">Submit all answers ${icon('check', 'h-5 w-5')}</button>`}</div></section>
      ${screenFooter('quiz')}`;
  };

  function resultsReview() {
    return `<section class="mt-7 space-y-4" aria-label="Answer review">${D.quizQuestions.map((q, i) => { const selected = Number(state.quiz.answers[i]); const correct = selected === q.answer; return `<article class="glass-card rounded-3xl p-5"><div class="flex items-start gap-3"><span class="grid h-9 w-9 shrink-0 place-items-center rounded-xl ${correct ? 'bg-emerald-400/10 text-emerald-300' : 'bg-rose-400/10 text-rose-300'}">${icon(correct ? 'check' : 'question', 'h-5 w-5')}</span><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><span class="text-xs font-black uppercase tracking-[.14em] ${correct ? 'text-emerald-300' : 'text-rose-300'}">Question ${i + 1} · ${correct ? 'Correct' : 'Review'}</span>${objectiveTag(q.objective)}</div><h3 class="mt-2 font-black leading-6 text-theme">${e(q.prompt)}</h3><div class="mt-4 grid gap-3 sm:grid-cols-2"><div class="rounded-2xl border border-theme bg-white/5 p-3"><p class="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">Your answer</p><p class="mt-1 text-sm ${correct ? 'text-emerald-200' : 'text-rose-200'}">${e(q.options[selected])}</p></div><div class="rounded-2xl border border-emerald-300/20 bg-emerald-400/10 p-3"><p class="text-[10px] font-black uppercase tracking-[.12em] text-emerald-300">Correct answer</p><p class="mt-1 text-sm text-theme">${e(q.options[q.answer])}</p></div></div><p class="mt-4 text-sm leading-6 text-muted-theme">${e(q.explanation)}</p>${correct ? '' : `<button class="secondary-button mt-4 min-h-0 px-3 py-2 text-xs" data-nav="${q.objective === 'O1' ? 'foundations' : 'algorithms'}">Remediate ${q.objective} ${icon('arrowright', 'h-4 w-4')}</button>`}</div></div></article>`; }).join('')}</section>`;
  }

  screens.results = function () {
    if (!state.quiz.submitted) {
      return `${screenHeader('results', 'No submitted mastery attempt is available yet. Complete all eight questions to generate objective-level evidence and review feedback.')}<section class="glass-card rounded-3xl p-8 text-center"><span class="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-slate-400/10 text-slate-400">${icon('clipboard', 'h-8 w-8')}</span><h2 class="mt-5 text-2xl font-black text-theme">Results will appear here</h2><p class="mx-auto mt-3 max-w-xl leading-7 text-muted-theme">The results screen reports overall mastery, performance on both objectives, item explanations, attempt history, and recommended review paths.</p><button class="primary-button mt-6" data-nav="quiz">Open mastery check ${icon('arrowright', 'h-5 w-5')}</button></section>${screenFooter('results')}`;
    }
    const stats = objectiveStats();
    const pass = state.quiz.lastPercent >= 80;
    const last = state.quiz.history[state.quiz.history.length - 1];
    const score = last ? last.score : Math.round((state.quiz.lastPercent / 100) * D.quizQuestions.length);
    return `${screenHeader('results', 'Use the score as evidence, not merely a finish line. Review objective performance and every missed item before choosing the next action.')}
      <section class="mesh-panel rounded-3xl border ${pass ? 'border-emerald-300/20' : 'border-amber-300/20'} p-6 sm:p-8"><div class="grid items-center gap-7 lg:grid-cols-[auto_1fr_auto]"><div>${progressRing(state.quiz.lastPercent, 120)}</div><div><span class="inline-flex items-center gap-2 rounded-full ${pass ? 'bg-emerald-400/10 text-emerald-200' : 'bg-amber-300/10 text-amber-100'} px-3 py-1.5 text-xs font-black">${icon(pass ? 'trophy' : 'question', 'h-4 w-4')} ${pass ? 'Mastery criterion reached' : 'Review recommended before retake'}</span><h2 class="mt-4 text-3xl font-black text-white">${score} of ${D.quizQuestions.length} correct</h2><p class="mt-2 text-sm leading-6 text-slate-300">Most recent: ${state.quiz.lastPercent}% · Best: ${state.quiz.bestPercent}% · Criterion: 80%</p></div><div class="flex flex-col gap-3"><button class="primary-button" data-action="quiz-retry">Retake assessment</button><button class="secondary-button" data-action="export-progress">${icon('download', 'h-4 w-4')} Export progress</button></div></div></section>
      <section class="mt-6 grid gap-4 md:grid-cols-2">${D.objectives.map(obj => { const stat = stats[obj.id]; const mastered = stat.percent >= 80; return `<article class="glass-card rounded-3xl p-5 sm:p-6"><div class="flex items-center justify-between gap-3"><span>${objectiveTag(obj.id)}</span><span class="text-3xl font-black ${mastered ? 'text-emerald-300' : 'text-amber-300'}">${stat.percent}%</span></div><div class="mt-4 h-2 overflow-hidden rounded-full bg-slate-800"><div class="h-full rounded-full ${mastered ? 'bg-emerald-400' : 'bg-amber-300'}" style="width:${stat.percent}%"></div></div><p class="mt-4 text-sm leading-6 text-muted-theme">${mastered ? `Evidence supports ${obj.label.toLowerCase()} on this attempt.` : obj.id === 'O1' ? 'Review labels versus no labels versus action-and-reward interaction.' : 'Review the required output, data, interpretability, and algorithm tradeoffs.'}</p><button class="secondary-button mt-4 w-full text-xs" data-nav="${obj.id === 'O1' ? 'foundations' : 'algorithms'}">${mastered ? 'Optional review' : 'Recommended remediation'} ${icon('arrowright', 'h-4 w-4')}</button></article>`; }).join('')}</section>
      <section class="mt-7 glass-card rounded-3xl p-5 sm:p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-black uppercase tracking-[.16em] text-cyan-300">Item-level evidence</p><h2 class="mt-1 text-2xl font-black text-theme">Review explanations and remediation</h2><p class="mt-2 text-sm text-muted-theme">Incorrect responses include a direct branch to the relevant concept or algorithm screen.</p></div><button class="secondary-button shrink-0" data-action="quiz-review">${icon(state.quiz.reviewMode ? 'eye' : 'book', 'h-5 w-5')}${state.quiz.reviewMode ? 'Hide review' : 'Show answer review'}</button></div>${state.quiz.reviewMode ? resultsReview() : ''}</section>
      <section class="mt-7 grid gap-5 lg:grid-cols-[1fr_.7fr]"><div class="glass-card rounded-3xl p-5"><h2 class="font-black text-theme">Attempt history</h2><div class="mt-4 space-y-3">${state.quiz.history.slice().reverse().map((item, index) => `<div class="flex items-center justify-between rounded-2xl border border-theme bg-white/5 p-3"><div><p class="text-sm font-black text-theme">Attempt ${state.quiz.history.length - index}</p><p class="text-xs text-muted-theme">${new Date(item.date).toLocaleString()}</p></div><span class="text-xl font-black ${item.percent >= 80 ? 'text-emerald-300' : 'text-amber-300'}">${item.percent}%</span></div>`).join('')}</div></div><div class="rounded-3xl border border-violet-300/20 bg-violet-400/10 p-5"><h2 class="flex items-center gap-2 font-black text-theme">${icon('route', 'h-5 w-5 text-violet-300')} Recommended next action</h2><p class="mt-3 text-sm leading-6 text-muted-theme">${pass && stats.O1.percent >= 80 && stats.O2.percent >= 80 ? 'Continue to Progress, export your learning record, and use the glossary as a reference.' : stats.O1.percent < stats.O2.percent ? 'Revisit Foundations and the three category lessons, then repeat Guided Practice.' : 'Revisit the Algorithm Explorer and Scenario Lab, then repeat Guided Practice.'}</p><button class="primary-button mt-5 w-full" data-nav="${pass ? 'progress' : stats.O1.percent < stats.O2.percent ? 'foundations' : 'algorithms'}">Open recommendation ${icon('arrowright', 'h-5 w-5')}</button></div></section>
      ${screenFooter('results')}`;
  };

  screens.progress = function () {
    const metrics = completionMetrics();
    const badges = earnedBadges();
    const stats = objectiveStats();
    return `${screenHeader('progress', 'This screen turns app activity into a transparent learning record. Progress is stored locally and can be exported as a JSON file.')}
      <section class="mesh-panel rounded-3xl border border-cyan-300/20 p-6 sm:p-8"><div class="grid items-center gap-7 lg:grid-cols-[auto_1fr_auto]"><div>${progressRing(metrics.percent, 124)}</div><div><p class="text-xs font-black uppercase tracking-[.16em] text-cyan-200">Overall completion</p><h2 class="mt-2 text-3xl font-black text-white">${metrics.complete} of ${metrics.total} milestones</h2><p class="mt-2 text-sm leading-6 text-slate-300">${e(state.profile.name || 'Learner')} · ${xpTotal()} XP · preferred session ${e(state.profile.minutes)} minutes</p><p class="mt-1 text-xs text-slate-400">Goal: ${e(state.profile.goal)}</p></div><div class="flex flex-col gap-3"><button class="primary-button" data-action="export-progress">${icon('download', 'h-5 w-5')} Export record</button><button class="secondary-button" data-action="open-settings">${icon('settings', 'h-5 w-5')} Settings</button></div></div></section>
      <section class="mt-7 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><article class="glass-card rounded-3xl p-5 sm:p-6"><div class="flex items-end justify-between"><div><p class="text-xs font-black uppercase tracking-[.16em] text-cyan-300">Learning milestones</p><h2 class="mt-1 text-xl font-black text-theme">Activity record</h2></div><span class="text-xs text-muted-theme">Saved automatically</span></div><div class="mt-5 space-y-3">${[
        ['Foundations', state.completedLessons.includes('foundations'),'foundations'],['Supervised learning',state.completedLessons.includes('supervised'),'supervised'],['Unsupervised learning',state.completedLessons.includes('unsupervised'),'unsupervised'],['Reinforcement learning',state.completedLessons.includes('reinforcement'),'reinforcement'],['Algorithm explorer',state.exploredAlgorithms.length>=3,'algorithms'],['Scenario lab',state.scenario.completed.length>=D.scenarios.length,'scenario'],['Guided practice',state.practice.complete,'practice'],['Mastery check',state.quiz.submitted,'quiz']
      ].map(item => `<button class="flex w-full items-center gap-3 rounded-2xl border border-theme bg-white/5 p-3 text-left" data-nav="${item[2]}"><span class="grid h-9 w-9 place-items-center rounded-xl ${item[1] ? 'bg-emerald-400/10 text-emerald-300' : 'bg-slate-400/10 text-slate-500'}">${icon(item[1] ? 'check' : 'lock', 'h-4 w-4')}</span><span class="flex-1 text-sm font-black text-theme">${item[0]}</span>${icon('chevronright', 'h-4 w-4 text-slate-500')}</button>`).join('')}</div></article><aside class="space-y-5"><div class="glass-card rounded-3xl p-5"><p class="text-xs font-black uppercase tracking-[.16em] text-violet-300">Mastery evidence</p><div class="mt-5 space-y-5">${D.objectives.map(obj => { const percent = state.quiz.submitted ? stats[obj.id].percent : 0; return `<div><div class="flex items-center justify-between gap-3"><span class="text-sm font-black text-theme">${obj.id} · ${e(obj.label)}</span><span class="text-sm font-black ${percent >= 80 ? 'text-emerald-300' : 'text-muted-theme'}">${percent}%</span></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-slate-800"><div class="h-full rounded-full bg-gradient-to-r from-cyan-400 to-violet-400" style="width:${percent}%"></div></div></div>`; }).join('')}</div><div class="mt-5 grid grid-cols-2 gap-3"><div class="rounded-2xl border border-theme bg-white/5 p-3 text-center"><p class="text-xl font-black text-theme">${state.practice.best}/${D.practiceQuestions.length}</p><p class="text-[10px] font-bold text-muted-theme">Practice best</p></div><div class="rounded-2xl border border-theme bg-white/5 p-3 text-center"><p class="text-xl font-black text-theme">${state.quiz.bestPercent}%</p><p class="text-[10px] font-bold text-muted-theme">Quiz best</p></div></div></div><div class="rounded-3xl border border-cyan-300/20 bg-cyan-400/10 p-5"><h2 class="flex items-center gap-2 font-black text-theme">${icon('shield', 'h-5 w-5 text-cyan-300')} Data and privacy</h2><p class="mt-2 text-sm leading-6 text-muted-theme">No account or network request is used for learner data. Reset removes this prototype’s localStorage record from the current browser.</p></div></aside></section>
      <section class="mt-7"><div class="flex items-end justify-between"><div><p class="text-xs font-black uppercase tracking-[.16em] text-amber-300">Achievements</p><h2 class="mt-1 text-2xl font-black text-theme">${badges.length} of ${D.badges.length} badges earned</h2></div></div><div class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">${D.badges.map(b => { const earned = badges.some(x => x.id === b.id); return `<article class="rounded-3xl border border-theme p-5 ${earned ? 'bg-amber-300/10' : 'bg-white/5 opacity-55'}"><div class="flex items-start gap-4"><span class="grid h-12 w-12 shrink-0 place-items-center rounded-2xl ${earned ? 'bg-amber-300/15 text-amber-300' : 'bg-slate-400/10 text-slate-500'}">${icon(earned ? b.icon : 'lock', 'h-6 w-6')}</span><div><div class="flex flex-wrap items-center gap-2"><h3 class="font-black text-theme">${e(b.title)}</h3>${statusChip(earned, ['Earned','Locked'])}</div><p class="mt-2 text-sm leading-6 text-muted-theme">${e(b.description)}</p></div></div></article>`; }).join('')}</div></section>
      ${screenFooter('progress')}`;
  };

  screens.glossary = function () {
    const categories = ['All', ...Array.from(new Set(D.glossary.map(item => item.category)))];
    const query = state.glossary.query.trim().toLowerCase();
    const terms = D.glossary.filter(item => (state.glossary.category === 'All' || item.category === state.glossary.category) && (!query || item.term.toLowerCase().includes(query) || item.definition.toLowerCase().includes(query)));
    return `${screenHeader('glossary', 'Search plain-language definitions while working through lessons, scenarios, or assessment feedback. Definitions are written for beginners and emphasize how each term is used in this prototype.')}
      <section class="glass-card rounded-3xl p-4 sm:p-5"><div class="grid gap-3 md:grid-cols-[1fr_auto]"><label class="relative"><span class="sr-only">Search glossary</span><span class="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400">${icon('search', 'h-5 w-5')}</span><input id="glossary-search" type="search" value="${e(state.glossary.query)}" placeholder="Search terms or definitions" class="w-full rounded-2xl border border-theme bg-white/5 py-3.5 pl-12 pr-4 text-theme placeholder:text-slate-500"></label><label><span class="sr-only">Filter by category</span><select id="glossary-category" class="w-full rounded-2xl border border-theme bg-white/5 px-4 py-3.5 text-theme">${categories.map(cat => `<option value="${e(cat)}" ${state.glossary.category === cat ? 'selected' : ''}>${e(cat)}</option>`).join('')}</select></label></div><p class="mt-3 text-xs text-muted-theme" aria-live="polite">${terms.length} of ${D.glossary.length} terms shown</p></section>
      <section class="mt-5 grid gap-4 md:grid-cols-2">${terms.length ? terms.map(item => `<article class="glass-card rounded-3xl p-5"><div class="flex items-start justify-between gap-3"><h2 class="text-lg font-black text-theme">${e(item.term)}</h2><span class="rounded-full bg-violet-400/10 px-2.5 py-1 text-[10px] font-black uppercase tracking-[.1em] text-violet-200">${e(item.category)}</span></div><p class="mt-3 text-sm leading-6 text-muted-theme">${e(item.definition)}</p></article>`).join('') : `<div class="col-span-full rounded-3xl border border-theme bg-white/5 p-10 text-center"><span class="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-slate-400/10 text-slate-400">${icon('search', 'h-6 w-6')}</span><h2 class="mt-4 text-xl font-black text-theme">No matching terms</h2><p class="mt-2 text-sm text-muted-theme">Try a broader keyword or change the category filter.</p></div>`}</section>
      ${screenFooter('glossary')}`;
  };

  screens.resources = function () {
    return `${screenHeader('resources', 'Use these tools during review or after completing the prototype. The downloadable decision guide works as a compact job aid outside the app.')}
      <section class="grid gap-4 md:grid-cols-2">${D.resources.map(resource => `<article class="glass-card rounded-3xl p-5 sm:p-6"><div class="flex items-start gap-4"><span class="icon-shell">${icon(resource.icon, 'h-5 w-5')}</span><div class="flex-1"><p class="text-[10px] font-black uppercase tracking-[.14em] text-cyan-300">${e(resource.type)}</p><h2 class="mt-1 text-xl font-black text-theme">${e(resource.title)}</h2><p class="mt-2 text-sm leading-6 text-muted-theme">${e(resource.description)}</p></div></div>${resource.action === 'download-guide' ? `<button class="primary-button mt-5 w-full" data-action="download-guide">${icon('download', 'h-5 w-5')} Download decision guide</button>` : `<button class="secondary-button mt-5 w-full" data-nav="${resource.action}">Open resource ${icon('arrowright', 'h-5 w-5')}</button>`}</article>`).join('')}</section>
      <section class="mt-7 grid gap-5 lg:grid-cols-[1fr_.85fr]"><article class="glass-card rounded-3xl p-5 sm:p-6"><p class="text-xs font-black uppercase tracking-[.16em] text-violet-300">Model selection checklist</p><h2 class="mt-1 text-2xl font-black text-theme">Ask seven questions before naming an algorithm</h2><ol class="mt-5 grid gap-3 sm:grid-cols-2">${[
        ['1','Decision','What real decision or user need will the output support?'],['2','Signal','Are there labels, unlabeled features, or sequential rewards?'],['3','Output','Do we need a class, number, group, representation, or action policy?'],['4','Evidence','What metric and held-out evaluation match the cost of errors?'],['5','Constraints','How important are interpretability, latency, memory, and maintainability?'],['6','Responsibility','What privacy, fairness, safety, and human-oversight risks exist?'],['7','Monitoring','How will drift, failures, and unintended impact be detected after use?']
      ].map(item => `<li class="rounded-2xl border border-theme bg-white/5 p-4"><span class="text-xs font-black text-cyan-300">${item[0]} · ${item[1]}</span><p class="mt-2 text-xs leading-5 text-muted-theme">${item[2]}</p></li>`).join('')}</ol></article><aside class="space-y-5"><div class="mesh-panel rounded-3xl border border-cyan-300/20 p-5"><h2 class="flex items-center gap-2 font-black text-white">${icon('brain', 'h-5 w-5 text-cyan-300')} Retrieval practice routine</h2><ol class="mt-4 space-y-3 text-sm leading-6 text-slate-300"><li><strong class="text-white">1.</strong> Hide the notes and explain the three categories from memory.</li><li><strong class="text-white">2.</strong> Invent one labeled, one unlabeled, and one reward-based scenario.</li><li><strong class="text-white">3.</strong> Name the required output before selecting an algorithm.</li><li><strong class="text-white">4.</strong> Check your reasoning in the explorer or glossary.</li></ol></div><div class="rounded-3xl border border-amber-300/20 bg-amber-300/10 p-5"><h2 class="flex items-center gap-2 font-black text-theme">${icon('info', 'h-5 w-5 text-amber-300')} Prototype scope</h2><p class="mt-2 text-sm leading-6 text-muted-theme">This app teaches conceptual task framing and introductory algorithm matching. It does not train production models, validate a real dataset, or replace statistical, ethical, security, and domain review.</p></div></aside></section>
      ${screenFooter('resources')}`;
  };

  screens.about = function () {
    return `${screenHeader('about', 'ML Learning Companion is a self-instructional, mobile-first prototype created for college students and adult learners who are new to machine learning.')}
      <section class="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><article class="glass-card rounded-3xl p-6 sm:p-7"><p class="text-xs font-black uppercase tracking-[.16em] text-cyan-300">Purpose and audience</p><h2 class="mt-2 text-2xl font-black text-theme">Decision literacy before technical depth</h2><p class="mt-4 leading-7 text-muted-theme">The prototype helps a beginner inspect a problem’s evidence, identify its learning category, and connect a small set of common algorithms to suitable outputs and applications. It deliberately prioritizes conceptual accuracy, explainable reasoning, and active practice over code or mathematical derivations.</p><div class="mt-6 space-y-4">${D.objectives.map(obj => `<div class="rounded-2xl border border-theme bg-white/5 p-4"><div class="flex items-center gap-2">${objectiveTag(obj.id)}</div><p class="mt-3 text-sm leading-6 text-muted-theme">${e(obj.text)}</p></div>`).join('')}</div></article><aside class="mesh-panel rounded-3xl border border-violet-300/20 p-6"><p class="text-xs font-black uppercase tracking-[.16em] text-violet-200">Prototype facts</p><dl class="mt-5 space-y-4">${[
        ['Version',D.version],['Screens','17 distinct screens'],['Core lessons','4'],['Interactive cases','4'],['Practice items','6 with immediate feedback'],['Mastery items','8 with delayed feedback'],['Persistence','Browser localStorage'],['Technology','HTML, Tailwind CSS, vanilla JavaScript']
      ].map(row => `<div class="flex items-start justify-between gap-4 border-b border-white/10 pb-3"><dt class="text-sm text-slate-400">${row[0]}</dt><dd class="text-right text-sm font-black text-white">${row[1]}</dd></div>`).join('')}</dl></aside></section>
      <section class="mt-7"><p class="text-xs font-black uppercase tracking-[.16em] text-cyan-300">Self-instruction and navigation</p><h2 class="mt-1 text-2xl font-black text-theme">Every user path has a clear next action</h2><div class="mt-4 grid gap-4 md:grid-cols-3">${[
        ['route','Persistent navigation','Desktop sidebar, mobile menu, bottom navigation, Back/Next controls, and direct remediation links.'],['question','Anticipated support','Directions on every activity, visible progress, plain-language feedback, glossary search, and reset controls.'],['shield','Accessible interaction','Semantic headings, keyboard focus, labeled controls, skip link, reduced motion, light/dark themes, and live feedback regions.']
      ].map(item => `<article class="rounded-3xl border border-theme bg-white/5 p-5"><span class="icon-shell">${icon(item[0], 'h-5 w-5')}</span><h3 class="mt-4 font-black text-theme">${item[1]}</h3><p class="mt-2 text-sm leading-6 text-muted-theme">${item[2]}</p></article>`).join('')}</div></section>
      <section class="mt-7 glass-card rounded-3xl p-5 sm:p-6"><div class="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-xs font-black uppercase tracking-[.16em] text-violet-300">Screen inventory</p><h2 class="mt-1 text-xl font-black text-theme">Seventeen linked screens</h2><p class="mt-2 text-sm text-muted-theme">All screens remain available from the menu, regardless of navigation path.</p></div><div class="flex flex-wrap gap-2">${D.screenOrder.map((id, i) => `<button class="rounded-full border border-theme bg-white/5 px-3 py-1.5 text-xs font-bold text-muted-theme hover:text-cyan-300" data-nav="${id}">${i + 1}. ${e(D.screenInfo[id].title)}</button>`).join('')}</div></div></section>
      <section class="mt-7 grid gap-5 md:grid-cols-2"><div class="rounded-3xl border border-emerald-300/20 bg-emerald-400/10 p-5"><h2 class="flex items-center gap-2 font-black text-theme">${icon('accessibility', 'h-5 w-5 text-emerald-300')} Accessibility controls</h2><p class="mt-2 text-sm leading-6 text-muted-theme">Use Settings to toggle theme and motion. The interface respects operating-system reduced-motion preferences unless full motion is explicitly selected.</p><button class="secondary-button mt-4" data-action="open-settings">Open settings</button></div><div class="rounded-3xl border border-cyan-300/20 bg-cyan-400/10 p-5"><h2 class="flex items-center gap-2 font-black text-theme">${icon('library', 'h-5 w-5 text-cyan-300')} Need a term or decision aid?</h2><p class="mt-2 text-sm leading-6 text-muted-theme">The glossary and downloadable category guide are designed for use at the moment of need.</p><div class="mt-4 flex flex-wrap gap-3"><button class="secondary-button" data-nav="glossary">Open glossary</button><button class="primary-button" data-action="download-guide">Download guide</button></div></div></section>
      ${screenFooter('about')}`;
  };
})();
