/* Onboarding, dashboard, path, concept lessons, and algorithm explorer. */
(function () {
  'use strict';
  const A = window.MLC;
  const { D, state, screens, icon, escapeHTML: e, screenHeader, screenFooter, objectiveTag, statusChip, progressRing, completionMetrics, xpTotal, markLesson, clusterPoints } = A;

  function directionBox(items) {
    return `<section class="mb-7 rounded-2xl border border-cyan-300/20 bg-cyan-400/10 p-4 sm:p-5" aria-labelledby="directions-heading"><div class="flex gap-3"><span class="mt-0.5 text-cyan-300">${icon('route', 'h-5 w-5')}</span><div><h2 id="directions-heading" class="text-sm font-black text-theme">How to complete this screen</h2><ol class="mt-2 space-y-1.5 text-sm leading-6 text-muted-theme">${items.map((item, i) => `<li><span class="mr-1 font-black text-cyan-300">${i + 1}.</span> ${item}</li>`).join('')}</ol></div></div></section>`;
  }

  function knowledgeCheck(config) {
    const result = state.checks[config.id];
    return `<section class="mt-7 rounded-3xl border border-theme bg-white/5 p-5 sm:p-6" aria-labelledby="${config.id}-heading">
      <div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-[.16em] text-violet-300">Quick check</p><h2 id="${config.id}-heading" class="mt-1 text-xl font-black text-theme">${e(config.prompt)}</h2></div>${result ? statusChip(result.correct, [result.correct ? 'Correct' : 'Review needed', '']) : '<span class="rounded-full bg-slate-400/10 px-3 py-1 text-xs font-bold text-slate-400">Choose one answer</span>'}</div>
      <div class="mt-5 grid gap-3">${config.options.map((option, index) => {
        let cls = 'choice-card border-theme bg-white/5';
        if (result) {
          if (index === config.correct) cls = 'choice-card correct';
          else if (index === result.value && !result.correct) cls = 'choice-card incorrect';
        }
        return `<button class="${cls} flex w-full items-start gap-3 rounded-2xl border p-4 text-left" data-action="lesson-answer" data-check="${config.id}" data-value="${index}" data-correct="${config.correct}" ${result ? 'disabled' : ''}><span class="grid h-7 w-7 shrink-0 place-items-center rounded-full border border-theme text-xs font-black text-muted-theme">${String.fromCharCode(65 + index)}</span><span class="pt-0.5 text-sm font-bold leading-6 text-theme">${e(option)}</span></button>`;
      }).join('')}</div>
      ${result ? `<div class="mt-5 rounded-2xl border p-4 ${result.correct ? 'feedback-correct' : 'feedback-incorrect'}"><div class="flex gap-3"><span class="mt-0.5 ${result.correct ? 'text-emerald-300' : 'text-rose-300'}">${icon(result.correct ? 'check' : 'question', 'h-5 w-5')}</span><div><p class="font-black text-theme">${result.correct ? 'That is the best answer.' : 'This distinction needs another look.'}</p><p class="mt-1 text-sm leading-6 text-muted-theme">${e(result.correct ? config.explanation : config.misconception)}</p>${!result.correct ? `<button class="secondary-button mt-3 min-h-0 px-3 py-2 text-xs" data-nav="${config.remediation}">Review ${e(D.screenInfo[config.remediation].title)} ${icon('arrowright', 'h-4 w-4')}</button>` : ''}</div></div></div>` : ''}
    </section>`;
  }

  function completionPanel(screen, message) {
    const done = state.completedLessons.includes(screen);
    return `<section class="mt-7 mesh-panel rounded-3xl border border-cyan-300/20 p-5 sm:p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex items-center gap-2">${statusChip(done)} ${objectiveTag(D.screenInfo[screen].module === 'learn' ? 'O1' : 'O2')}</div><h2 class="mt-3 text-xl font-black text-theme">${done ? 'Lesson saved to your learning record' : 'Ready to mark this lesson complete?'}</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-muted-theme">${message}</p></div><button class="${done ? 'secondary-button' : 'primary-button'} shrink-0" data-action="mark-complete" data-screen="${screen}" ${done ? 'disabled' : ''}>${icon(done ? 'check' : 'trophy', 'h-5 w-5')}${done ? 'Completed' : 'Complete lesson'}</button></div></section>`;
  }

  screens.welcome = function () {
    return `<section class="glass-card relative w-full max-w-6xl overflow-hidden rounded-[2rem] p-5 sm:p-8 lg:p-12">
      <div class="absolute -right-28 -top-28 h-80 w-80 rounded-full bg-violet-500/20 blur-3xl"></div><div class="absolute -bottom-36 -left-20 h-80 w-80 rounded-full bg-cyan-500/20 blur-3xl"></div>
      <div class="relative grid items-center gap-10 lg:grid-cols-[1.08fr_.92fr]">
        <div>
          <div class="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-400/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.16em] text-cyan-200">${icon('sparkles', 'h-4 w-4')} Interactive learning prototype</div>
          <h1 id="screen-title" tabindex="-1" class="mt-6 text-4xl font-black tracking-[-.04em] text-theme sm:text-6xl lg:text-7xl">Machine learning,<br><span class="gradient-text">made navigable.</span></h1>
          <p class="mt-6 max-w-2xl text-base leading-7 text-muted-theme sm:text-lg">ML Learning Companion is a self-paced, mobile-first experience that helps beginners identify the three primary learning categories and match practical algorithms to real problems.</p>
          <div class="mt-7 grid gap-3 sm:grid-cols-2">${D.objectives.map(obj => `<div class="rounded-2xl border border-theme bg-white/5 p-4"><div class="flex items-center gap-2 text-sm font-black text-theme"><span class="text-cyan-300">${icon(obj.icon, 'h-5 w-5')}</span>${obj.id}: ${e(obj.label)}</div><p class="mt-2 text-xs leading-5 text-muted-theme">${e(obj.short)}</p></div>`).join('')}</div>
          <div class="mt-8 flex flex-col gap-3 sm:flex-row"><button class="primary-button pulse-soft px-5 py-4" data-action="start-app">Build my learning plan ${icon('arrowright', 'h-5 w-5')}</button><button class="secondary-button px-5 py-4" data-nav="about">${icon('info', 'h-5 w-5')} Preview app features</button></div>
          <p class="mt-4 flex items-center gap-2 text-xs text-muted-theme">${icon('clock', 'h-4 w-4 text-emerald-300')} About 55 minutes total · progress saves automatically</p>
        </div>
        <div class="relative mx-auto w-full max-w-md">
          <div class="float-slow absolute -left-5 top-20 z-20 rounded-2xl border border-cyan-300/20 bg-slate-900/90 p-3 shadow-2xl backdrop-blur-xl"><div class="flex items-center gap-2"><span class="grid h-8 w-8 place-items-center rounded-xl bg-emerald-400/10 text-emerald-300">${icon('check', 'h-4 w-4')}</span><div><p class="text-xs font-black text-theme">Instant feedback</p><p class="text-[10px] text-slate-400">Why, not just right/wrong</p></div></div></div>
          <div class="float-slow absolute -right-4 bottom-20 z-20 rounded-2xl border border-violet-300/20 bg-slate-900/90 p-3 shadow-2xl backdrop-blur-xl" style="animation-delay:-2s"><div class="flex items-center gap-2"><span class="grid h-8 w-8 place-items-center rounded-xl bg-violet-400/10 text-violet-300">${icon('trophy', 'h-4 w-4')}</span><div><p class="text-xs font-black text-theme">Mastery evidence</p><p class="text-[10px] text-slate-400">Objective-level results</p></div></div></div>
          <div class="relative mx-auto w-[84%] rounded-[2.6rem] border-[7px] border-slate-800 bg-slate-950 p-3 shadow-[0_35px_80px_rgba(2,6,23,.55)]"><div class="mx-auto mb-3 h-5 w-24 rounded-full bg-slate-800"></div><div class="mesh-panel min-h-[31rem] rounded-[1.8rem] p-5"><div class="flex items-center justify-between"><span class="grid h-10 w-10 place-items-center rounded-2xl bg-cyan-300 text-slate-950">${icon('brain', 'h-5 w-5')}</span><span class="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[10px] font-black text-cyan-200">LEVEL 1</span></div><p class="mt-8 text-xs font-black uppercase tracking-[.2em] text-cyan-300">Today’s path</p><h2 class="mt-2 text-2xl font-black text-white">See the problem.<br>Choose the learning type.</h2><div class="mt-6 space-y-3">${[['tags','Supervised','Labeled examples'],['cluster','Unsupervised','Hidden structure'],['gamepad','Reinforcement','Actions + rewards']].map((x,i) => `<div class="rounded-2xl border ${i === 0 ? 'border-cyan-300/30 bg-cyan-400/10' : 'border-white/10 bg-white/5'} p-3"><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-xl bg-white/5 text-cyan-200">${icon(x[0], 'h-4 w-4')}</span><div><p class="text-sm font-black text-white">${x[1]}</p><p class="text-[11px] text-slate-400">${x[2]}</p></div></div></div>`).join('')}</div><div class="mt-6 rounded-2xl bg-gradient-to-r from-cyan-300 to-emerald-300 p-3 text-center text-sm font-black text-slate-950">Continue lesson →</div></div></div>
        </div>
      </div>
    </section>`;
  };

  screens.profile = function () {
    return `<section class="glass-card w-full max-w-5xl overflow-hidden rounded-[2rem]"><div class="grid lg:grid-cols-[.85fr_1.15fr]"><div class="mesh-panel p-6 sm:p-9"><button class="ghost-button min-h-0 px-0 py-2" data-nav="welcome">${icon('arrowleft', 'h-5 w-5')} Back</button><span class="mt-12 grid h-14 w-14 place-items-center rounded-2xl bg-cyan-300 text-slate-950">${icon('user', 'h-7 w-7')}</span><h1 id="screen-title" tabindex="-1" class="mt-5 text-3xl font-black text-white sm:text-4xl">Set your learning plan</h1><p class="mt-4 leading-7 text-slate-300">Your choices personalize the dashboard. They do not change the assessment criteria or share data outside this browser.</p><div class="mt-8 space-y-4">${D.objectives.map(obj => `<div class="flex gap-3"><span class="mt-1 text-cyan-300">${icon('check', 'h-5 w-5')}</span><p class="text-sm leading-6 text-slate-200"><strong>${obj.id}</strong> · ${e(obj.short)}</p></div>`).join('')}</div></div>
      <div class="p-6 sm:p-9"><form id="profile-form" class="space-y-6"><div><label for="learner-name" class="text-sm font-black text-theme">What should the companion call you?</label><input id="learner-name" name="name" type="text" maxlength="40" value="${e(state.profile.name)}" placeholder="Your name" class="mt-2 w-full rounded-2xl border border-theme bg-white/5 px-4 py-3.5 text-theme placeholder:text-slate-500" autocomplete="name"></div><fieldset><legend class="text-sm font-black text-theme">Choose your primary goal</legend><div class="mt-3 grid gap-3">${[
        ['Build practical machine learning literacy','I want a clear foundation for work or study.'],
        ['Prepare to discuss ML with a technical team','I need useful vocabulary and decision rules.'],
        ['Explore a possible data or AI career','I want to test my interest with hands-on examples.']
      ].map((goal, i) => `<label class="choice-card flex cursor-pointer gap-3 rounded-2xl border border-theme bg-white/5 p-4"><input class="mt-1 h-4 w-4 accent-cyan-400" type="radio" name="goal" value="${e(goal[0])}" ${(state.profile.goal === goal[0] || (!state.profile.complete && i === 0)) ? 'checked' : ''}><span><span class="block text-sm font-black text-theme">${e(goal[0])}</span><span class="mt-1 block text-xs leading-5 text-muted-theme">${e(goal[1])}</span></span></label>`).join('')}</div></fieldset><div><label for="session-minutes" class="text-sm font-black text-theme">Preferred session length</label><select id="session-minutes" name="minutes" class="mt-2 w-full rounded-2xl border border-theme bg-white/5 px-4 py-3.5 text-theme"><option value="10" ${state.profile.minutes === '10' ? 'selected' : ''}>10 minutes — one focused activity</option><option value="15" ${state.profile.minutes === '15' ? 'selected' : ''}>15 minutes — recommended pace</option><option value="25" ${state.profile.minutes === '25' ? 'selected' : ''}>25 minutes — two or three activities</option></select></div><div class="rounded-2xl border border-emerald-300/20 bg-emerald-400/10 p-4"><p class="flex gap-2 text-xs leading-5 text-emerald-100">${icon('shield', 'mt-0.5 h-4 w-4 shrink-0 text-emerald-300')} Progress is stored only in this browser using localStorage. You can export or reset it from Progress.</p></div><button class="primary-button w-full py-4" type="submit">Save plan and open dashboard ${icon('arrowright', 'h-5 w-5')}</button></form></div></div></section>`;
  };

  screens.home = function () {
    const metrics = completionMetrics();
    const next = D.lessonCards.find(item => !state.completedLessons.includes(item.id) && (item.id !== 'scenario' || state.scenario.completed.length < D.scenarios.length) && (item.id !== 'quiz' || !state.quiz.submitted)) || D.lessonCards[D.lessonCards.length - 1];
    const firstName = e((state.profile.name || 'Learner').split(/\s+/)[0]);
    const badges = A.earnedBadges();
    return `${screenHeader('home', `Welcome back, <strong class="text-theme">${firstName}</strong>. Continue in sequence or jump to any available activity from the menu.`)}
      <section class="mesh-panel rounded-3xl border border-cyan-300/20 p-5 sm:p-7"><div class="grid items-center gap-6 lg:grid-cols-[1fr_auto]"><div><div class="flex flex-wrap items-center gap-2"><span class="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs font-black text-cyan-200">Recommended next</span>${objectiveTag(next.objective === 'O1 + O2' ? 'O2' : next.objective)}</div><h2 class="mt-4 text-2xl font-black text-white sm:text-3xl">${e(next.title)}</h2><p class="mt-2 max-w-2xl leading-7 text-slate-300">${e(next.description)}</p><div class="mt-5 flex flex-wrap gap-3"><button class="primary-button" data-nav="${next.id}">${icon('play', 'h-5 w-5')} Continue · ${next.duration} min</button><button class="secondary-button" data-nav="path">View full learning path</button></div></div><div class="mx-auto flex items-center gap-4 rounded-3xl border border-white/10 bg-slate-950/35 p-4">${progressRing(metrics.percent, 86)}<div><p class="text-3xl font-black text-white">${metrics.complete}<span class="text-base text-slate-400">/${metrics.total}</span></p><p class="text-xs font-bold uppercase tracking-[.12em] text-slate-400">milestones</p></div></div></div></section>
      <section class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">${[
        ['bolt', `${xpTotal()} XP`, 'Knowledge and activity points', 'text-amber-300'],
        ['check', `${state.completedLessons.length} complete`, 'Lessons saved', 'text-emerald-300'],
        ['target', `${state.practice.best}/${D.practiceQuestions.length}`, 'Best practice score', 'text-cyan-300'],
        ['trophy', `${state.quiz.bestPercent || 0}%`, 'Best mastery score', 'text-violet-300']
      ].map(item => `<article class="glass-card rounded-2xl p-4"><span class="${item[3]}">${icon(item[0], 'h-5 w-5')}</span><p class="mt-4 text-xl font-black text-theme">${item[1]}</p><p class="mt-1 text-xs leading-5 text-muted-theme">${item[2]}</p></article>`).join('')}</section>
      <section class="mt-8 grid min-w-0 gap-6 lg:grid-cols-[1.25fr_.75fr]"><div class="min-w-0"><div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-[.16em] text-cyan-300">Core sequence</p><h2 class="mt-1 text-2xl font-black text-theme">Learn → apply → assess</h2></div><button class="ghost-button text-xs" data-nav="path">See all ${icon('arrowright', 'h-4 w-4')}</button></div><div class="mt-4 space-y-3">${D.lessonCards.slice(0, 4).map(item => { const done = state.completedLessons.includes(item.id); return `<button class="glass-card group flex w-full items-center gap-4 rounded-2xl p-4 text-left" data-nav="${item.id}"><span class="grid h-11 w-11 place-items-center rounded-2xl ${done ? 'bg-emerald-400/10 text-emerald-300' : 'bg-cyan-400/10 text-cyan-300'}">${icon(done ? 'check' : D.screenInfo[item.id].icon, 'h-5 w-5')}</span><span class="min-w-0 flex-1"><span class="block text-sm font-black text-theme">${item.step} · ${e(item.title)}</span><span class="mt-1 block truncate text-xs text-muted-theme">${e(item.description)}</span></span><span class="text-slate-500 transition group-hover:translate-x-1 group-hover:text-cyan-300">${icon('chevronright', 'h-5 w-5')}</span></button>`; }).join('')}</div></div>
      <aside class="space-y-5"><div class="glass-card rounded-3xl p-5"><div class="flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-[.16em] text-violet-300">Achievements</p><h2 class="mt-1 text-xl font-black text-theme">${badges.length} of ${D.badges.length} earned</h2></div><span class="text-amber-300">${icon('trophy', 'h-7 w-7')}</span></div><div class="mt-4 grid grid-cols-3 gap-2">${D.badges.slice(0, 6).map(b => { const earned = badges.some(x => x.id === b.id); return `<div class="rounded-2xl border border-theme p-3 text-center ${earned ? 'bg-amber-300/10' : 'bg-white/5 opacity-45'}" title="${e(b.description)}"><span class="mx-auto grid h-8 w-8 place-items-center rounded-xl ${earned ? 'text-amber-300' : 'text-slate-500'}">${icon(earned ? b.icon : 'lock', 'h-5 w-5')}</span><p class="mt-1 truncate text-[10px] font-black text-theme">${e(b.title)}</p></div>`; }).join('')}</div><button class="secondary-button mt-4 w-full text-xs" data-nav="progress">Open progress record</button></div><div class="rounded-3xl border border-emerald-300/20 bg-emerald-400/10 p-5"><h2 class="flex items-center gap-2 font-black text-theme">${icon('route', 'h-5 w-5 text-emerald-300')} How to use this app</h2><ol class="mt-3 space-y-2 text-sm leading-6 text-muted-theme"><li><strong class="text-theme">1.</strong> Read each lesson and use its interactive model.</li><li><strong class="text-theme">2.</strong> Answer the quick check and review feedback.</li><li><strong class="text-theme">3.</strong> Complete practice before the mastery check.</li></ol></div></aside></section>
      ${screenFooter('home')}`;
  };

  screens.path = function () {
    const totalMinutes = D.lessonCards.reduce((sum, item) => sum + item.duration, 0);
    return `${screenHeader('path', 'Follow the recommended order for maximum scaffolding. Every screen remains available so you can review concepts whenever feedback identifies a gap.', `<span class="rounded-full bg-white/5 px-2.5 py-1 text-slate-400">${totalMinutes} min total</span>`)}
      ${directionBox(['Start with Foundations and move downward through the sequence.', 'Use each activity’s quick check or interaction before marking it complete.', 'Complete Guided Practice before the Mastery Check; use Results to choose remediation.'])}
      <section class="relative"><div class="absolute bottom-8 left-[1.35rem] top-8 hidden w-px bg-gradient-to-b from-cyan-400 via-violet-400 to-emerald-400 sm:block"></div><div class="space-y-4">${D.lessonCards.map((item, index) => {
        let done = state.completedLessons.includes(item.id);
        if (item.id === 'scenario') done = state.scenario.completed.length >= D.scenarios.length;
        if (item.id === 'quiz') done = state.quiz.submitted;
        const current = !done && D.lessonCards.slice(0, index).every(prev => state.completedLessons.includes(prev.id) || (prev.id === 'scenario' && state.scenario.completed.length >= D.scenarios.length));
        return `<article class="glass-card relative rounded-3xl p-4 sm:ml-16 sm:p-5 ${current ? 'border-cyan-300/40' : ''}"><span class="absolute -left-[4rem] top-5 hidden h-11 w-11 place-items-center rounded-full border-4 border-slate-950 font-black sm:grid ${done ? 'bg-emerald-400 text-slate-950' : current ? 'bg-cyan-300 text-slate-950 pulse-soft' : 'bg-slate-800 text-slate-400'}">${done ? icon('check', 'h-5 w-5') : item.step}</span><div class="flex flex-col gap-4 sm:flex-row sm:items-center"><span class="grid h-12 w-12 shrink-0 place-items-center rounded-2xl ${done ? 'bg-emerald-400/10 text-emerald-300' : 'bg-white/5 text-cyan-300'}">${icon(D.screenInfo[item.id].icon, 'h-6 w-6')}</span><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h2 class="text-lg font-black text-theme">${e(item.title)}</h2>${statusChip(done, ['Complete', current ? 'Recommended' : 'Available'])}</div><p class="mt-1 text-sm leading-6 text-muted-theme">${e(item.description)}</p><div class="mt-2 flex flex-wrap items-center gap-2 text-xs text-slate-400"><span class="flex items-center gap-1">${icon('clock', 'h-3.5 w-3.5')} ${item.duration} min</span><span>·</span><span>${e(item.objective)}</span></div></div><button class="${current ? 'primary-button' : 'secondary-button'} shrink-0" data-nav="${item.id}">${done ? 'Review' : current ? 'Start' : 'Open'} ${icon('arrowright', 'h-4 w-4')}</button></div></article>`;
      }).join('')}</div></section>
      <section class="mt-8 grid gap-4 md:grid-cols-3">${[
        ['brain','Learn','Build a mental model with concise explanations, examples, and visual representations.'],
        ['flask','Apply','Make category and algorithm choices in authentic scenarios with branching feedback.'],
        ['chart','Assess','Use practice, a mastery check, and objective-level results to decide what to review.']
      ].map(item => `<div class="rounded-3xl border border-theme bg-white/5 p-5"><span class="icon-shell">${icon(item[0], 'h-5 w-5')}</span><h2 class="mt-4 font-black text-theme">${item[1]}</h2><p class="mt-2 text-sm leading-6 text-muted-theme">${item[2]}</p></div>`).join('')}</section>
      ${screenFooter('path')}`;
  };

  screens.foundations = function () {
    return `${screenHeader('foundations', 'Build the vocabulary needed to reason about any machine learning problem. The central question is not “Which algorithm is popular?” but “What evidence and output does this task require?”', objectiveTag('O1'))}
      ${directionBox(['Read the definition and inspect the five-stage workflow.', 'Compare features, labels, and predictions in the example.', 'Answer the quick check, review its explanation, and then mark the lesson complete.'])}
      <section class="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><article class="glass-card rounded-3xl p-5 sm:p-7"><p class="text-xs font-black uppercase tracking-[.16em] text-cyan-300">Core idea</p><h2 class="mt-2 text-2xl font-black text-theme">Machine learning finds a useful pattern from data or experience.</h2><p class="mt-4 leading-7 text-muted-theme">Instead of writing every decision rule by hand, a developer defines a task, represents relevant information as data, selects a learning method, and evaluates whether the learned pattern generalizes to new cases.</p><div class="mt-6 rounded-2xl border border-amber-300/20 bg-amber-300/10 p-4"><p class="text-sm leading-6 text-amber-100"><strong>Important:</strong> “Learning” does not mean understanding like a person. A model optimizes a mathematical objective under the information, examples, and feedback it receives.</p></div></article><aside class="mesh-panel rounded-3xl border border-violet-300/20 p-5 sm:p-7"><p class="text-xs font-black uppercase tracking-[.16em] text-violet-200">Problem-first decision rule</p><div class="mt-5 space-y-3">${[
        ['Known target for past examples?','Supervised learning','tags'],
        ['No target; discover structure?','Unsupervised learning','cluster'],
        ['Actions plus rewards over time?','Reinforcement learning','gamepad']
      ].map(item => `<div class="rounded-2xl border border-white/10 bg-slate-950/30 p-4"><p class="text-xs font-bold text-slate-400">${item[0]}</p><div class="mt-2 flex items-center gap-2 font-black text-white"><span class="text-cyan-300">${icon(item[2], 'h-5 w-5')}</span>${item[1]}</div></div>`).join('')}</div></aside></section>
      <section class="mt-7"><div class="flex items-end justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-[.16em] text-cyan-300">Workflow</p><h2 class="mt-1 text-2xl font-black text-theme">From problem to monitored use</h2></div><span class="hidden text-xs text-muted-theme sm:block">Scroll horizontally on small screens</span></div><div class="custom-scrollbar mt-4 flex snap-x gap-3 overflow-x-auto pb-3">${[
        ['1','Frame','Define the decision, user, constraints, and cost of errors.','target'],
        ['2','Represent','Collect examples and encode relevant information as features.','blocks'],
        ['3','Train','Fit model parameters using examples, targets, or rewards.','brain'],
        ['4','Evaluate','Test on unseen data with metrics aligned to the real decision.','chart'],
        ['5','Monitor','Track drift, failures, fairness, privacy, and human impact.','eye']
      ].map(item => `<article class="glass-card w-[16rem] shrink-0 snap-start rounded-2xl p-4"><div class="flex items-center justify-between"><span class="text-xs font-black text-cyan-300">STEP ${item[0]}</span><span class="text-slate-400">${icon(item[4], 'h-5 w-5')}</span></div><h3 class="mt-4 text-lg font-black text-theme">${item[1]}</h3><p class="mt-2 text-sm leading-6 text-muted-theme">${item[2]}</p></article>`).join('')}</div></section>
      <section class="mt-7 grid gap-4 md:grid-cols-3">${[
        ['Feature','Input information the model can use.','Study minutes, prior score, device type','blocks'],
        ['Label / target','The known outcome in supervised learning.','Completed course: yes or no','tags'],
        ['Prediction / output','What the trained model produces for new input.','72% completion probability','trend']
      ].map(item => `<article class="rounded-3xl border border-theme bg-white/5 p-5"><span class="icon-shell">${icon(item[3], 'h-5 w-5')}</span><h2 class="mt-4 font-black text-theme">${item[0]}</h2><p class="mt-2 text-sm leading-6 text-muted-theme">${item[1]}</p><p class="mt-4 rounded-xl bg-slate-950/30 p-3 text-xs leading-5 text-slate-300"><strong>Example:</strong> ${item[2]}</p></article>`).join('')}</section>
      ${knowledgeCheck({ id: 'foundations-check', prompt: 'Which statement best describes a feature?', options: ['The score used to evaluate a model', 'An input variable available to the model', 'The known outcome in every kind of machine learning', 'A guarantee that a prediction is correct'], correct: 1, explanation: 'Features are the input variables used to represent each example. In supervised learning, a separate label or target provides the outcome to predict.', misconception: 'A feature is input information. A metric evaluates performance, while a label is a supervised target—not a requirement for every ML category.', remediation: 'foundations' })}
      ${completionPanel('foundations', 'Mark complete after you can distinguish a feature, a supervised label, a model output, and an evaluation metric.')}
      ${screenFooter('foundations')}`;
  };

  screens.supervised = function () {
    return `${screenHeader('supervised', 'Supervised learning uses examples paired with known outcomes. The model learns a mapping from features to a target, then applies that mapping to new cases.', objectiveTag('O1'))}
      ${directionBox(['Compare classification and regression by their output type.', 'Trace the labeled-example visual and read the train/validate/test note.', 'Use the decision rule in the quick check, then complete the lesson.'])}
      <section class="grid gap-5 md:grid-cols-2"><article class="glass-card rounded-3xl p-6"><div class="flex items-center justify-between"><span class="icon-shell">${icon('split', 'h-5 w-5')}</span><span class="rounded-full bg-cyan-400/10 px-3 py-1 text-xs font-black text-cyan-200">Categorical output</span></div><h2 class="mt-5 text-2xl font-black text-theme">Classification</h2><p class="mt-3 leading-7 text-muted-theme">Predict a class or class probability: spam/not spam, at-risk/on-track, cat/dog, or one of several support queues.</p><div class="mt-5 rounded-2xl border border-theme bg-white/5 p-4"><p class="text-xs font-black uppercase tracking-[.14em] text-slate-400">Question to ask</p><p class="mt-2 font-bold text-theme">“Which category should this example belong to?”</p></div></article><article class="glass-card rounded-3xl p-6"><div class="flex items-center justify-between"><span class="icon-shell">${icon('trend', 'h-5 w-5')}</span><span class="rounded-full bg-violet-400/10 px-3 py-1 text-xs font-black text-violet-200">Continuous output</span></div><h2 class="mt-5 text-2xl font-black text-theme">Regression</h2><p class="mt-3 leading-7 text-muted-theme">Predict a numeric amount: price, minutes, temperature, demand, energy use, or a future assessment score.</p><div class="mt-5 rounded-2xl border border-theme bg-white/5 p-4"><p class="text-xs font-black uppercase tracking-[.14em] text-slate-400">Question to ask</p><p class="mt-2 font-bold text-theme">“How much, how many, or how long?”</p></div></article></section>
      <section class="mt-7 mesh-panel rounded-3xl border border-cyan-300/20 p-5 sm:p-7"><div class="grid items-center gap-8 lg:grid-cols-[.9fr_1.1fr]"><div><p class="text-xs font-black uppercase tracking-[.16em] text-cyan-200">Labeled-example loop</p><h2 class="mt-2 text-2xl font-black text-white">Features and labels teach the mapping.</h2><p class="mt-3 leading-7 text-slate-300">Suppose each historical learner record contains study behavior features and a known completion outcome. Training adjusts the model so its predictions better match those known outcomes.</p><div class="mt-5 space-y-3 text-sm text-slate-300"><p class="flex gap-2">${icon('check', 'mt-0.5 h-4 w-4 shrink-0 text-emerald-300')} <span><strong class="text-white">Training set:</strong> fit the pattern.</span></p><p class="flex gap-2">${icon('check', 'mt-0.5 h-4 w-4 shrink-0 text-emerald-300')} <span><strong class="text-white">Validation set:</strong> compare choices and tune settings.</span></p><p class="flex gap-2">${icon('check', 'mt-0.5 h-4 w-4 shrink-0 text-emerald-300')} <span><strong class="text-white">Test set:</strong> estimate performance on unseen data.</span></p></div></div><div class="rounded-3xl border border-white/10 bg-slate-950/35 p-5"><div class="grid gap-3 sm:grid-cols-[1fr_auto_1fr]"><div class="space-y-2">${[['4 sessions','Completed'],['1 session','Not complete'],['6 sessions','Completed']].map(row => `<div class="rounded-xl border border-white/10 bg-white/5 p-3"><p class="text-xs text-slate-400">Feature: ${row[0]}</p><p class="mt-1 text-sm font-black text-cyan-200">Label: ${row[1]}</p></div>`).join('')}</div><div class="grid place-items-center text-violet-300">${icon('arrowright2', 'h-8 w-8 rotate-90 sm:rotate-0')}</div><div class="grid place-items-center rounded-2xl border border-violet-300/20 bg-violet-400/10 p-5 text-center"><span class="grid h-14 w-14 place-items-center rounded-2xl bg-violet-300 text-slate-950">${icon('brain', 'h-7 w-7')}</span><p class="mt-3 text-sm font-black text-white">Learned classifier</p><p class="mt-1 text-xs text-slate-400">New learner → probability + class</p></div></div></div></div></section>
      <section class="mt-7 grid gap-4 lg:grid-cols-3">${[
        ['Strength','Directly optimizes against the outcome you care about when labels are reliable.','check','text-emerald-300'],
        ['Risk','Labels can be costly, inconsistent, historically biased, or leaked from the future.','question','text-amber-300'],
        ['Evidence','Choose metrics that reflect class balance and the real cost of false positives and false negatives.','chart','text-cyan-300']
      ].map(item => `<article class="rounded-3xl border border-theme bg-white/5 p-5"><span class="${item[3]}">${icon(item[2], 'h-6 w-6')}</span><h2 class="mt-4 font-black text-theme">${item[0]}</h2><p class="mt-2 text-sm leading-6 text-muted-theme">${item[1]}</p></article>`).join('')}</section>
      ${knowledgeCheck({ id: 'supervised-check', prompt: 'A team has past apartment features and known monthly rents. It wants to estimate rent for new apartments. Which task is this?', options: ['Supervised classification', 'Supervised regression', 'Unsupervised clustering', 'Reinforcement learning'], correct: 1, explanation: 'The target is known for past examples and is continuous numeric rent, so the task is supervised regression.', misconception: 'Look at both the training signal and output type: known targets make it supervised, and a numeric amount makes it regression.', remediation: 'supervised' })}
      ${completionPanel('supervised', 'Complete this lesson when you can decide between classification and regression by identifying whether the target is categorical or continuous.')}
      ${screenFooter('supervised')}`;
  };

  screens.unsupervised = function () {
    const cluster = clusterPoints();
    return `${screenHeader('unsupervised', 'Unsupervised learning receives features without a target label. Its job is to reveal structure, create a more compact representation, or surface unusual patterns.', objectiveTag('O1'))}
      ${directionBox(['Compare clustering and dimensionality reduction.', 'Move the K slider and regenerate the visualization to see how an analyst’s choice affects segmentation.', 'Answer the quick check and mark the lesson complete.'])}
      <section class="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><article class="glass-card rounded-3xl p-5 sm:p-6"><p class="text-xs font-black uppercase tracking-[.16em] text-cyan-300">Two common goals</p><div class="mt-5 space-y-4"><div class="rounded-2xl border border-theme bg-white/5 p-4"><div class="flex items-center gap-3"><span class="icon-shell">${icon('cluster', 'h-5 w-5')}</span><div><h2 class="font-black text-theme">Clustering</h2><p class="text-xs text-muted-theme">Discover groups of similar examples.</p></div></div><p class="mt-3 text-sm leading-6 text-muted-theme">Useful for exploratory learner personas or behavior segments when no authoritative group labels already exist.</p></div><div class="rounded-2xl border border-theme bg-white/5 p-4"><div class="flex items-center gap-3"><span class="icon-shell">${icon('compress', 'h-5 w-5')}</span><div><h2 class="font-black text-theme">Dimensionality reduction</h2><p class="text-xs text-muted-theme">Represent many features with fewer dimensions.</p></div></div><p class="mt-3 text-sm leading-6 text-muted-theme">Useful for visualization, compression, noise reduction, or preprocessing—but transformed components may be hard to interpret.</p></div></div><div class="mt-5 rounded-2xl border border-amber-300/20 bg-amber-300/10 p-4"><p class="text-sm leading-6 text-amber-100"><strong>Interpret carefully:</strong> A cluster is a mathematical grouping under selected features, scaling, distance, and K. It is not automatically a meaningful human category.</p></div></article>
      <article class="glass-card rounded-3xl p-5 sm:p-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-[.16em] text-violet-300">Interactive model</p><h2 class="mt-1 text-xl font-black text-theme">K-means style segmentation</h2></div><button class="secondary-button min-h-0 px-3 py-2 text-xs" data-action="regen-clusters">${icon('refresh', 'h-4 w-4')} New sample</button></div><div class="mt-4 cluster-canvas overflow-hidden rounded-2xl border border-white/10 p-2"><svg viewBox="0 0 330 215" class="h-auto w-full" role="img" aria-label="${state.cluster.k} colored clusters of data points around dashed centers">${cluster.points.map((p, i) => `<circle class="cluster-dot" data-cluster="${p.cluster}" cx="${p.x.toFixed(1)}" cy="${p.y.toFixed(1)}" r="${i % 4 === 0 ? 5 : 4}" opacity=".86"></circle>`).join('')}${cluster.centers.map((c, i) => `<circle class="cluster-center" data-cluster="${i}" cx="${c[0]}" cy="${c[1]}" r="13"></circle><path d="M${c[0]-5} ${c[1]}h10M${c[0]} ${c[1]-5}v10" class="cluster-center" data-cluster="${i}"></path>`).join('')}</svg></div><label for="cluster-k" class="mt-5 flex items-center justify-between text-sm font-black text-theme"><span>Choose number of clusters, K</span><output class="rounded-full bg-cyan-400/10 px-3 py-1 text-cyan-200">K = ${state.cluster.k}</output></label><input id="cluster-k" class="mt-3 w-full accent-cyan-400" type="range" min="2" max="4" step="1" value="${state.cluster.k}"><div class="mt-4 grid grid-cols-3 gap-2 text-center text-[11px] text-muted-theme"><span>1. Assign to nearest center</span><span>2. Recompute centers</span><span>3. Repeat until stable</span></div><p class="mt-4 text-xs leading-5 text-muted-theme">Notice that changing K changes the answer even though the underlying sample is generated from the same kind of feature space. Domain review is required before treating clusters as useful segments.</p></article></section>
      <section class="mt-7 rounded-3xl border border-theme bg-white/5 p-5 sm:p-6"><h2 class="text-xl font-black text-theme">Before you trust an unsupervised pattern</h2><div class="mt-5 grid gap-4 md:grid-cols-4">${[
        ['Scale','Are feature units comparable?','trend'],['Stability','Do groups persist across seeds or samples?','refresh'],['Meaning','Can domain experts explain the pattern?','users'],['Use','Will the grouping support a responsible decision?','shield']
      ].map(item => `<div class="rounded-2xl border border-theme bg-slate-950/20 p-4"><span class="text-cyan-300">${icon(item[2], 'h-5 w-5')}</span><h3 class="mt-3 text-sm font-black text-theme">${item[0]}</h3><p class="mt-1 text-xs leading-5 text-muted-theme">${item[1]}</p></div>`).join('')}</div></section>
      ${knowledgeCheck({ id: 'unsupervised-check', prompt: 'Which problem is the clearest fit for unsupervised learning?', options: ['Predict final grades from labeled past records', 'Discover patterns in study behavior when no personas are labeled', 'Choose hints to maximize later mastery rewards', 'Classify support requests into known queues'], correct: 1, explanation: 'The study-behavior task asks the model to discover structure without a target label.', misconception: 'The other choices include a known supervised target or an action-and-reward sequence. Unsupervised learning is the option with features but no target label.', remediation: 'unsupervised' })}
      ${completionPanel('unsupervised', 'Complete this lesson when you can explain why a discovered cluster is an exploratory result—not an automatically valid label or causal explanation.')}
      ${screenFooter('unsupervised')}`;
  };

  screens.reinforcement = function () {
    const cells = Array.from({ length: 9 }, (_, i) => i);
    const goal = state.rl.position === 8;
    return `${screenHeader('reinforcement', 'Reinforcement learning concerns sequential choices. An agent observes a state, takes an action, receives a reward, and updates a policy to improve long-term return.', objectiveTag('O1'))}
      ${directionBox(['Read the agent–environment loop.', 'Guide the agent from start to goal; notice step costs, blocked states, and delayed reward.', 'Answer the quick check and complete the lesson.'])}
      <section class="grid gap-6 lg:grid-cols-[.95fr_1.05fr]"><article class="glass-card rounded-3xl p-5 sm:p-6"><p class="text-xs font-black uppercase tracking-[.16em] text-violet-300">Learning loop</p><div class="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div class="rounded-2xl border border-cyan-300/20 bg-cyan-400/10 p-4 text-center"><span class="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-cyan-300 text-slate-950">${icon('gamepad', 'h-6 w-6')}</span><p class="mt-3 font-black text-theme">Agent</p><p class="mt-1 text-xs text-muted-theme">Chooses an action using a policy</p></div><div class="space-y-5 text-center text-xs font-black text-slate-400"><div><span>Action</span>${icon('arrowright2', 'mx-auto mt-1 h-6 w-6 text-cyan-300')}</div><div>${icon('arrowleft2', 'mx-auto mb-1 h-6 w-6 text-violet-300')}<span>State + reward</span></div></div><div class="rounded-2xl border border-violet-300/20 bg-violet-400/10 p-4 text-center"><span class="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-violet-300 text-slate-950">${icon('route', 'h-6 w-6')}</span><p class="mt-3 font-black text-theme">Environment</p><p class="mt-1 text-xs text-muted-theme">Changes state and returns reward</p></div></div><div class="mt-6 space-y-3">${[
        ['State','What the agent currently knows about the situation.'],['Action','A choice available to the agent in that state.'],['Reward','A numeric signal after an action or outcome.'],['Policy','The strategy mapping states to actions.']
      ].map(item => `<div class="flex gap-3 rounded-xl border border-theme bg-white/5 p-3"><span class="font-black text-cyan-300">${item[0]}</span><span class="text-sm leading-6 text-muted-theme">${item[1]}</span></div>`).join('')}</div></article>
      <article class="glass-card rounded-3xl p-5 sm:p-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-[.16em] text-cyan-300">Policy challenge</p><h2 class="mt-1 text-xl font-black text-theme">Reach the goal efficiently</h2></div><button class="secondary-button min-h-0 px-3 py-2 text-xs" data-action="rl-reset">${icon('refresh', 'h-4 w-4')} Reset</button></div><div class="mt-4 grid grid-cols-3 overflow-hidden rounded-2xl border border-theme">${cells.map(i => { const blocked = i === 4; const agent = i === state.rl.position; const visited = state.rl.visited.includes(i); return `<div class="maze-cell relative grid place-items-center ${blocked ? 'bg-rose-400/10' : i === 8 ? 'bg-emerald-400/10' : visited ? 'bg-cyan-400/5' : 'bg-white/[.025]'}">${blocked ? `<span class="text-rose-300">${icon('close', 'h-7 w-7')}</span><span class="absolute bottom-1 text-[9px] font-bold text-rose-300">blocked</span>` : i === 8 ? `<span class="text-amber-300">${icon('star', 'h-7 w-7')}</span><span class="absolute bottom-1 text-[9px] font-bold text-emerald-300">+10 goal</span>` : ''}${agent ? `<span class="maze-agent absolute grid h-9 w-9 place-items-center rounded-full bg-cyan-300 text-slate-950 shadow-lg">${icon('gamepad', 'h-4 w-4')}</span>` : ''}${i === 0 ? '<span class="absolute left-1 top-1 text-[8px] font-black text-slate-500">START</span>' : ''}</div>`; }).join('')}</div><div class="mx-auto mt-5 grid w-44 grid-cols-3 gap-2"><span></span><button class="secondary-button min-h-0 px-3 py-2" data-action="rl-move" data-direction="up" aria-label="Move up">${icon('arrowup', 'h-5 w-5')}</button><span></span><button class="secondary-button min-h-0 px-3 py-2" data-action="rl-move" data-direction="left" aria-label="Move left">${icon('arrowleft2', 'h-5 w-5')}</button><button class="secondary-button min-h-0 px-3 py-2" data-action="rl-move" data-direction="down" aria-label="Move down">${icon('arrowdown', 'h-5 w-5')}</button><button class="secondary-button min-h-0 px-3 py-2" data-action="rl-move" data-direction="right" aria-label="Move right">${icon('arrowright2', 'h-5 w-5')}</button></div><div class="mt-5 grid grid-cols-2 gap-3"><div class="rounded-2xl border border-theme bg-white/5 p-3 text-center"><p class="text-xs font-bold text-muted-theme">Cumulative reward</p><p class="mt-1 text-2xl font-black ${state.rl.reward >= 0 ? 'text-emerald-300' : 'text-rose-300'}">${state.rl.reward > 0 ? '+' : ''}${state.rl.reward}</p></div><div class="rounded-2xl border border-theme bg-white/5 p-3 text-center"><p class="text-xs font-bold text-muted-theme">Valid moves</p><p class="mt-1 text-2xl font-black text-theme">${state.rl.moves}</p></div></div><p class="mt-4 rounded-2xl border ${goal ? 'border-emerald-300/30 bg-emerald-400/10 text-emerald-100' : 'border-cyan-300/20 bg-cyan-400/10 text-cyan-100'} p-3 text-xs leading-5" aria-live="polite">${e(state.rl.message)}</p></article></section>
      <section class="mt-7 grid gap-4 md:grid-cols-3">${[
        ['Explore','Try actions whose value is uncertain; otherwise the agent may never discover a better path.','search'],['Exploit','Use the best action known so far to collect reward efficiently.','target'],['Credit assignment','Connect delayed outcomes to earlier actions that helped produce them.','gitbranch']
      ].map(item => `<article class="rounded-3xl border border-theme bg-white/5 p-5"><span class="text-violet-300">${icon(item[2], 'h-6 w-6')}</span><h2 class="mt-4 font-black text-theme">${item[0]}</h2><p class="mt-2 text-sm leading-6 text-muted-theme">${item[1]}</p></article>`).join('')}</section>
      ${knowledgeCheck({ id: 'reinforcement-check', prompt: 'Which detail most clearly indicates a reinforcement-learning problem?', options: ['Every training example has a correct category label', 'The output is a numeric amount', 'An agent’s actions affect later states and rewards', 'The dataset has many feature columns'], correct: 2, explanation: 'Reinforcement learning is defined by interaction: actions change the environment, rewards evaluate outcomes, and the agent learns a policy for long-term return.', misconception: 'A numeric output or many features can occur in several categories. The distinctive pattern is repeated action, state transition, and reward.', remediation: 'reinforcement' })}
      ${completionPanel('reinforcement', 'Complete this lesson when you can identify the agent, environment, state, actions, rewards, and policy in a sequential decision problem.')}
      ${screenFooter('reinforcement')}`;
  };

  screens.algorithms = function () {
    const filter = state.algorithmFilter;
    const algorithms = D.algorithms.filter(a => filter === 'all' || a.family === filter || a.task.toLowerCase().includes(filter));
    const ready = state.exploredAlgorithms.length >= 3;
    return `${screenHeader('algorithms', 'Algorithms are tools, not interchangeable answers. Filter by learning family, inspect at least three detail cards, and compare the required input, output, strengths, and cautions.', objectiveTag('O2'))}
      ${directionBox(['Choose a filter or browse all eight algorithms.', 'Open at least three cards and compare task, input, output, fit, examples, and cautions.', 'Mark the explorer complete, then use the Scenario Lab to make a contextual choice.'])}
      <section class="glass-card rounded-3xl p-4 sm:p-5"><div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div class="flex items-center gap-3"><span class="icon-shell">${icon('filter', 'h-5 w-5')}</span><div><h2 class="font-black text-theme">Filter the catalog</h2><p class="text-xs text-muted-theme">${algorithms.length} algorithm${algorithms.length === 1 ? '' : 's'} shown</p></div></div><div class="flex flex-wrap gap-2">${[
        ['all','All'],['supervised','Supervised'],['unsupervised','Unsupervised'],['reinforcement','Reinforcement'],['classification','Classification'],['regression','Regression']
      ].map(item => `<button class="${filter === item[0] ? 'primary-button' : 'secondary-button'} min-h-0 px-3 py-2 text-xs" data-action="algorithm-filter" data-filter="${item[0]}">${item[1]}</button>`).join('')}</div></div></section>
      <section class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">${algorithms.map(a => { const viewed = state.exploredAlgorithms.includes(a.id); return `<button class="glass-card choice-card flex h-full flex-col rounded-3xl p-5 text-left" data-action="open-algorithm" data-id="${a.id}"><div class="flex w-full items-start justify-between gap-3"><span class="icon-shell">${icon(a.icon, 'h-5 w-5')}</span>${viewed ? statusChip(true, ['Viewed','']) : `<span class="rounded-full bg-white/5 px-2.5 py-1 text-[10px] font-black uppercase tracking-[.1em] text-slate-400">${e(a.difficulty)}</span>`}</div><p class="mt-5 text-[10px] font-black uppercase tracking-[.16em] ${a.family === 'supervised' ? 'text-cyan-300' : a.family === 'unsupervised' ? 'text-violet-300' : 'text-emerald-300'}">${e(a.family)} · ${e(a.task)}</p><h2 class="mt-2 text-xl font-black text-theme">${e(a.name)}</h2><p class="mt-2 flex-1 text-sm leading-6 text-muted-theme">${e(a.tagline)}</p><span class="mt-5 flex items-center gap-1 text-xs font-black text-cyan-300">Open detail card ${icon('arrowright', 'h-4 w-4')}</span></button>`; }).join('')}</section>
      <section class="mt-7 grid gap-5 lg:grid-cols-[1fr_auto]"><div class="rounded-3xl border border-violet-300/20 bg-violet-400/10 p-5"><div class="flex items-start gap-3"><span class="text-violet-300">${icon('question', 'h-6 w-6')}</span><div><h2 class="font-black text-theme">A responsible algorithm choice considers more than fit</h2><p class="mt-2 text-sm leading-6 text-muted-theme">After matching the task, compare data quantity and quality, evaluation evidence, interpretability needs, computational constraints, privacy, fairness, monitoring, and the consequences of error.</p></div></div></div><div class="glass-card min-w-[15rem] rounded-3xl p-5 text-center"><p class="text-xs font-black uppercase tracking-[.14em] text-slate-400">Detail cards explored</p><p class="mt-2 text-3xl font-black text-theme">${state.exploredAlgorithms.length}<span class="text-base text-slate-500">/3 minimum</span></p><button class="${ready ? 'primary-button' : 'secondary-button'} mt-4 w-full" data-action="mark-complete" data-screen="algorithms" ${ready ? '' : 'disabled'}>${ready ? icon('check', 'h-5 w-5') : icon('lock', 'h-5 w-5')}${state.completedLessons.includes('algorithms') ? 'Explorer complete' : ready ? 'Complete explorer' : 'Explore more cards'}</button></div></section>
      ${screenFooter('algorithms')}`;
  };
})();
